USE sakila;

-- 1.List the number of films per category.

SELECT c.name,
	COUNT(DISTINCT film_id) as number_of_films
FROM film_category fc
JOIN category c ON c.category_id=fc.category_id
GROUP BY fc.category_id;

-- 2.Retrieve the store ID, city, and country for each store.
SELECT s.store_id,
	ci.city,
    co.country
FROM store s
JOIN address a ON a.address_id=s.address_id
JOIN city ci ON ci.city_id=a.city_id
JOIN country co ON co.country_id=ci.country_id;

-- 3.Calculate the total revenue generated by each store in dollars.
SELECT s.store_id,
	SUM(p.amount) as total_revenue
FROM payment p
LEFT JOIN staff s ON s.staff_id = p.staff_id
GROUP BY s.store_id;

-- 4.Determine the average running time of films for each category.
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc
    ON c.category_id = fc.category_id
JOIN film f
    ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY average_running_time DESC;

-- 5.
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_running_time
FROM category c
JOIN film_category fc
    ON c.category_id = fc.category_id
JOIN film f
    ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY avg_running_time DESC;

-- 6 . 
SELECT
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i
    ON f.film_id = i.film_id
JOIN rental r
    ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 10;

-- 7. 
SELECT
    f.title,
    i.store_id,
    COUNT(*) AS copies_available
FROM film f
JOIN inventory i
    ON f.film_id = i.film_id
WHERE f.title = 'ACADEMY DINOSAUR'
  AND i.store_id = 1
GROUP BY f.title, i.store_id;

-- 8.
SELECT
    DISTINCT f.title,
    CASE
        WHEN IFNULL(i.film_id, 0) = 0
            THEN 'NOT available'
        ELSE 'Available'
    END AS availability_status
FROM film f
LEFT JOIN inventory i
    ON f.film_id = i.film_id
ORDER BY f.title;
